### ISSUE TITLE
Compatilibity with standalone v2022.10 Orchestrator

### ISSUE THREAD

**Issue by sik-asn** [UiPath/uipathcli#109]
Hello :sunny:

Can you tell me whether this CLI should work with standalone versions of Orchestrator v2022.10.2?

I am attempting to deploy a package for a robot to it, and I'm getting this error in a stacktrace:
```
19-02-2024 10:25:14	Executing <REDACTED>/uipcli.exe package deploy <REDACTED>\build https://<REDACTED>/ <REDACTED> --accountForApp admin --applicationId <REDACTED> --applicationSecret <REDACTED> --applicationScope "OR.ML OR.Monitoring.Write OR.Monitoring.Read OR.Monitoring OR.Webhooks.Write OR.Webhooks.Read OR.Webhooks OR.Audit.Write OR.Audit.Read OR.Audit OR.Administration.Write OR.Administration.Read OR.Administration OR.Users.Write OR.Users.Read OR.Users OR.Jobs.Write OR.Jobs.Read OR.Jobs OR.Queues.Write OR.Queues.Read OR.Queues OR.Assets.Write OR.ML.Read OR.ML.Write OR.Tasks OR.Tasks.Read OR.TestDataQueues.Write OR.TestDataQueues.Read OR.TestDataQueues OR.TestSetSchedules.Write OR.TestSetSchedules.Read OR.TestSetSchedules OR.TestSetExecutions.Write OR.TestSetExecutions.Read OR.TestSetExecutions OR.Assets.Read OR.TestSets.Write OR.TestSets OR.BackgroundTasks.Write OR.BackgroundTasks.Read OR.BackgroundTasks OR.Folders.Write OR.Folders.Read OR.Folders OR.Analytics.Write OR.Analytics.Read OR.Analytics OR.Tasks.Write OR.TestSets.Read OR.Assets OR.Execution.Write OR.Execution.Read OR.Execution OR.Machines.Write OR.Machines.Read OR.Machines OR.Robots.Write OR.Robots.Read OR.Robots OR.Settings.Write OR.Settings.Read OR.Settings OR.License.Write OR.License.Read OR.License OR.Hypervisor OR.Hypervisor.Read OR.Hypervisor.Write"
19-02-2024 10:25:14	-----------------------------------------------------------------------------
Failed to run the command. Could not connect to Cloud Orchestrator: https://<REDACTED>/, Account Name For App: admin, Application Id: <REDACTED>, Application Scope(s): OR.ML OR.Monitoring.Write OR.Monitoring.Read OR.Monitoring OR.Webhooks.Write OR.Webhooks.Read OR.Webhooks OR.Audit.Write OR.Audit.Read OR.Audit OR.Administration.Write OR.Administration.Read OR.Administration OR.Users.Write OR.Users.Read OR.Users OR.Jobs.Write OR.Jobs.Read OR.Jobs OR.Queues.Write OR.Queues.Read OR.Queues OR.Assets.Write OR.ML.Read OR.ML.Write OR.Tasks OR.Tasks.Read OR.TestDataQueues.Write OR.TestDataQueues.Read OR.TestDataQueues OR.TestSetSchedules.Write OR.TestSetSchedules.Read OR.TestSetSchedules OR.TestSetExecutions.Write OR.TestSetExecutions.Read OR.TestSetExecutions OR.Assets.Read OR.TestSets.Write OR.TestSets OR.BackgroundTasks.Write OR.BackgroundTasks.Read OR.BackgroundTasks OR.Folders.Write OR.Folders.Read OR.Folders OR.Analytics.Write OR.Analytics.Read OR.Analytics OR.Tasks.Write OR.TestSets.Read OR.Assets OR.Execution.Write OR.Execution.Read OR.Execution OR.Machines.Write OR.Machines.Read OR.Machines OR.Robots.Write OR.Robots.Read OR.Robots OR.Settings.Write OR.Settings.Read OR.Settings OR.License.Write OR.License.Read OR.License OR.Hypervisor OR.Hypervisor.Read OR.Hypervisor.Write, Tenant: sik, Organization Unit: .
Please make sure that the provided URL (https://<REDACTED>/) is correct, available from your build agent, and not blocked by a firewall.
If the Orchestrator is using a self-signed SSL certificate, make sure that the build agent trusts it. Ensure that all the steps at https://docs.uipath.com/orchestrator/docs/self-signed-certificates were correctly followed when creating the certificate.
Stack trace:
   at UiPath.CommandLine.Clients.OrchestratorClientFactory.<>c__DisplayClass5_0.<<BuildClient>g__HandleBuild|8>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Clients.OrchestratorClientFactory.BuildClient(BaseAuthenticatedOptions options, Boolean setOrganizationUnit)
   at UiPath.CommandLine.Services.Impl.DeployService.Run(DeployOptions options)
   at UiPath.CommandLine.Services.Impl.OptionsParser.<>c__DisplayClass7_0.<<WithTraceLogging>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Services.Impl.OptionsParser.RunOptions(String[] args, Func`3 notParsedFunc)
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code MethodNotAllowed
   at UiPath.Orchestrator.Client.Util.UiPathWebApiExtensions.MakeHttpRequest(UiPathWebApi api, HttpMethod method, String url, Object dto)
   at UiPath.Orchestrator.Client.Util.AuthenticatedClient.ApplicationAccessToken(AuthToken authToken)
   at UiPath.Orchestrator.Client.Util.AuthenticatedClient.MakeApi[T](AuthToken authToken, Func`3 ctor, TimeSpan timeout)
   at UiPath.Orchestrator.Client.OrchestratorClientFactory.SetOrchestratorServerVersion(AuthToken authToken, Int32 requestTimeout)
   at UiPath.Orchestrator.Client.OrchestratorClientFactory.BuildAsyncViaExternalApp(String url, String tenantName, String accountName, String applicationId, String applicationSecret, String applicationScope, String organizationUnit, CloudDeployments cloudDeployment, IDictionary`2 customHeaders, Int32 requestTimeout, String authorizationUrl, Boolean setOrganizationUnit, TextWriter outWriter)
   at UiPath.CommandLine.Clients.OrchestratorClientFactory.<>c__DisplayClass5_0.<<BuildClient>g__HandleBuild|8>d.MoveNext()
19-02-2024 10:25:15	Unable to deploy project. Exit code 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
```

**Comment by thschmitt** [comment]
`uipcli.exe` is a different command line tool, see [here](https://docs.uipath.com/automation-ops/automation-cloud/latest/user-guide/uipath-command-line-interface). You can look at the [compatibility matrix](https://docs.uipath.com/automation-ops/automation-cloud/latest/user-guide/uipath-command-line-interface#uipathcli-compatibility-matrix) to verify if your CLI version works with orchestrator v2022.10.2.
